const atharvProducts = [
    { name: "Lexi Pen (10 Pieces)", price: 60 },
    { name: "Montex Mega Top Pen (10 Pieces)", price: 90 },
    { name: "Cello Griper Pen(10 Pieces)", price: 90 },
    { name: "Cello Pin Point (10 Pieces)", price: 90 },
    { name: "Use and Throw Pen Fort (20 Pieces)", price: 70 },
    { name: "Reynolds Gel Pen (1 Pieces)", price: 12 },
    { name: "Cello Flow Gel Pen", price: 12 },
    { name: "Uniball Micro Gel Pen", price: 70 },
    { name: "Camel Marker OHP", price: 9 },
    { name: "A4 Sparkle Paper (70GSM)", price: 240 },
    { name: "A4 Sparkle Paper (75GSM)", price: 260 },
    { name: "A4 B2B Paper (70GSM)", price: 250 },
    { name: "A4 Alpha Power Paper (75GSM)", price: 250 },
    { name: "A4 JK Red Paper (75GSM)", price: 270 },
    { name: "FC Sparkle Paper (70GSM)", price: 330 },
    { name: "FC Ledger Paper (75GSM)", price: 390 },
    { name: "A4 Sticker Paper (1 Box = 100 piece)", price: 320 },
    { name: "A4 Photo Paper (180 GSM, 20 piece)", price: 100 },
    { name: "A5 Paper Sparkle (70GSM)", price: 180 },
    { name: "A4 Executive Bond Paper (80GSM)", price: 120 },
    { name: "1 QR Register (Sunny)", price: 70 },
    { name: "2 QR Register (Sunny)", price: 140 },
    { name: "5 QR Register (Sunny)", price: 350 },
    { name: "1 QR Register Rexin Binding", price: 80 },
    { name: "2 QR Register Rexin Binding", price: 160 },
    { name: "5 QR Register Rexin Binding", price: 400 },
    { name: "Note Book (100 pg)", price: 20 },
    { name: "Note Book (200 pg.)", price: 30 },
    { name: "Long Book (100 pg.)", price: 25 },
    { name: "Long Book (200 pg.)", price: 40 },
    { name: "A4 College Book (100 pg.)", price: 30 },
    { name: "A4 College Book (200 pg.)", price: 50 },
    { name: "Dairy (7 No.)", price: 150 },
    { name: "Dairy (8 No.)", price: 170 },
    { name: "Scribbling Pad 40 pg. (1/16)", price: 15 },
    { name: "Scribbling Pad 40 pg. (1/12)", price: 25 },
    { name: "Scribbling Pad 40 pg. (1/8)", price: 30 },
    { name: "Scribbling Pad 40 pg. (1/6)", price: 50 },
    { name: "Scribbling Pad 40 pg. (A4)", price: 80 },
    { name: "Conference Pad 10 Pg.(1/8)", price: 10 },
    { name: "Full-scale Paper Rim (20 Dozen)", price: 380 },
    { name: "Cash Voucher Book (50Sheets)", price: 35 },
    { name: "Debit Voucher Book (50 Sheets)", price: 35 },
    { name: "Receipt Book (100 Sheets)", price: 60 },
    { name: "Simple File", price: 20 },
    { name: "Spring File", price: 20 },
    { name: "Cloth Patti Spring File", price: 30 },
    { name: "2 Flap File", price: 25 },
    { name: "4 Flap File", price: 40 },
    { name: "Less File (2 piece)", price: 45 },
    { name: "Voucher File", price: 70 },
    { name: "Box File (Kangaroo Clip)", price: 70 },
    { name: "College File", price: 15 },
    { name: "A4 Ring File", price: 50 },
    { name: "FC Ring File", price: 60 },
    { name: "A4 Plastic File", price: 50 },
    { name: "FC Plastic File", price: 60 },
    { name: "Punch Folder FC", price: 8 },
    { name: "L Folder A4", price: 8 },
    { name: "L Folder FC", price: 12 },
    { name: "Button Folder", price: 30 },
    { name: "Button Folder Side Patti", price: 50 },
    { name: "Button Folder Check Folder", price: 35 },
    { name: "A4 Plastic Spring File", price: 40 },
    { name: "FC Plastic Spring File", price: 50 },
    { name: "12 Folder File", price: 110 },
    { name: "24 Folder File", price: 180 },
    { name: "10 Folder Zip File", price: 200 },
    { name: "20 Folder Zip File", price: 250 },
    { name: "12 Folder Zip File", price: 150 },
    { name: "A4 40pg Display File", price: 60 },
    { name: "A4 80pg Display File", price: 90 },
    { name: "Check Paino Folder", price: 30 },
    { name: "Paino File", price: 200 },
    { name: "Paino File (High Quality)", price: 250 },
    { name: "Binder Clips (15mm)", price: 30 },
    { name: "Binder Clips (19mm)", price: 40 },
    { name: "Binder Clips (25mm)", price: 60 },
    { name: "Binder Clips (32mm)", price: 100 },
    { name: "Binder Clips (41mm)", price: 120 },
    { name: "Binder Clips (51mm)", price: 180 },
    { name: "9.5x4.5 White Envelop (100)", price: 150 },
    { name: "9.5x4.5 Brown Envelop (100)", price: 150 },
    { name: "11x5 White Envelop (100)", price: 200 },
    { name: "11X5 Brown Envelop (100)", price: 200 },
    { name: "A4 White Envelop (100)", price: 450 },
    { name: "A4 Brown Envelop (100)", price: 450 },
    { name: "5x7 White Envelop (100)", price: 350 },
    { name: "6x9 White Envelop (100)", price: 45 },
    { name: "5x11 Cloth Envelop (100)", price: 450 },
    { name: "7 X 9 Cloth Envelop (100)", price: 750 },
    { name: "8X 10.5Cloth Envelop (100)", price: 850 },
    { name: "10X12 Cloth Envelop (100)", price: 950 },
    { name: "10.5 X 14 Cloth Envelop (100)", price: 1200 },
    { name: "12X16 Cloth Envelop (100)", price: 1500 },
    { name: "14 X 18 Cloth Envelop (100)", price: 1800 },
    { name: "CD Mailer Brown Envelop (10 Piece)", price: 60 },
    { name: "12 Digit Calculator (Low Quality)", price: 120 },
    { name: "12 Digit Calculator (Medium Quality)", price: 200 },
    { name: "12 Digit Calculator (High Quality)", price: 450 },
    { name: "Casio Calculator", price: 460 },
    { name: "Citizen Calculator", price: 460 },
    { name: "Stapler 10", price: 60 },
    { name: "Stapler HD 45", price: 150 },
    { name: "Stapler HD10", price: 180 },
    { name: "Stapler HP 45", price: 250 },
    { name: "Stapler TP-10", price: 450 },
    { name: "Stapler Pin 10No.(1Box=20Pieces)", price: 170 },
    { name: "Stapler Pin 24x6(1Box=20Pieces)", price: 240 },
    { name: "Stapler pin 23X13", price: 60 },
    { name: "Punch Machine DP 52", price: 90 },
    { name: "Punch Machine DP 280", price: 100 },
    { name: "Punch Machine DP 480", price: 160 },
    { name: "Punch Machine DP 500", price: 180 },
    { name: "Single Side Punch Machine FP 20", price: 110 },
    { name: "Carbon Paper Box", price: 190 },
    { name: "Double Carbon Paper Box", price: 190 },
    { name: "Fevicol 22.5 g", price: 9 },
    { name: "Fevicol 45g", price: 22 },
    { name: "Fevicol 100g", price: 50 },
    { name: "Fevistick 5g", price: 13 },
    { name: "Fevistick 8g", price: 22 },
    { name: "Fevistick 15g", price: 35 },
    { name: "Fevistick 25g", price: 45 },
    { name: "Fevikwick 5/-", price: 5 },
    { name: "Fevikwick 10/-", price: 9 },
    { name: "Fevikwick 20/-", price: 16 },
    { name: "Fevibond 8g", price: 12 },
    { name: "Fevibond 25g", price: 22 },
    { name: "Everyday AA Cell", price: 15 },
    { name: "Everyday AAA Cell", price: 15 },
    { name: "Duracell AA Cell", price: 18 },
    { name: "Duracell AAA Cell", price: 18 },
    { name: "Everyday Big Cell", price: 35 },
    { name: "9 W Cell", price: 25 },
    { name: "2025 Cell", price: 30 },
    { name: "2032 Cell", price: 30 },
    { name: "Post It (1 Color)", price: 40 },
    { name: "Post It (3 Color)", price: 30 },
    { name: "Post It (4 Color)", price: 30 },
    { name: "Pin (50g)", price: 25 },
    { name: "Pin(100g)", price: 90 },
    { name: "U pin Box(28mm)", price: 250 },
    { name: "U pin Box(35mm)", price: 350 },
    { name: "U pin Plastic Coated", price: 350 },
    { name: "T Pin (50 g)", price: 40 },
    { name: "Cutter 10/-", price: 8 },
    { name: "Cutter 20/-", price: 16 },
    { name: "Cuter 18mm", price: 50 },
    { name: "Plastic Keychain (50 Piece)", price: 100 },
    { name: "Drawing pin", price: 30 },
    { name: "Drawing Pin Steel", price: 40 },
    { name: "Rubber Band (Size: 14,16,19) 500GM", price: 350 },
    { name: "Scissor Small", price: 50 },
    { name: "Scissor Medium", price: 60 },
    { name: "Scissor 7.No.", price: 100 },
    { name: "Scissor 8.No.", price: 130 },
    { name: "Scissor Metal 8No.", price: 350 },
    { name: "Black Board Duster Small", price: 15 },
    { name: "Black Board Duster Big", price: 30 },
    { name: "White Board Duster", price: 70 },
    { name: "White Board Magnet", price: 80 },
    { name: "Glue Gun Machine", price: 250 },
    { name: "Glue Gun Sticks", price: 10 },
    { name: "White Thread (1 Box = 4 Piece)", price: 30 },
    { name: "Green Thread (1 Box = 4 Piece)", price: 30 },
    { name: "Orange Binding Thread (1 Box = 6 Piece)", price: 70 },
    { name: "Plastic Scale (12 inch) Camel", price: 10 },
    { name: "Plastic Scale (12 inch) Fiber Castle", price: 17 },
    { name: "Steel Scale (6 inch)", price: 30 },
    { name: "Steel Scale (12 inch)", price: 40 },
    { name: "Steel Scale (24 inch)", price: 110 },
    { name: "Air Freshener", price: 90 },
    { name: "White Tag Box", price: 50 },
    { name: "White Tag Cotton Bundle", price: 90 },
    { name: "White Tag Nylon Bundle", price: 90 },
    { name: "Red Tag Box", price: 200 },
    { name: "Steel torch", price: 40 },
    { name: "Steel Clip (small) (12 piece)", price: 80 },
    { name: "Steel Clip (Medium) (12 piece)", price: 120 },
    { name: "Steel Clip (Big) (12 piece)", price: 200 },
    { name: "Plastic Clip (12 piece)", price: 120 },
    { name: "Camel Stamp Pad 9.5X3 cm", price: 30 },
    { name: "Camel Stamp Pad 11X7 cm", price: 50 },
    { name: "Camel Stamp Pad 15.7X9.7 cm", price: 70 },
    { name: "Camel Stamp Pad Ink(25ml)", price: 30 },
    { name: "Camel Stamp Pad Ink(100ml)", price: 120 },
    { name: "Camel Highlighter (5 Color)", price: 100 },
    { name: "Camel Paste (150ml)", price: 30 },
    { name: "Camel Paste (300ml)", price: 50 },
    { name: "Camel Paste (700ml)", price: 70 },
    { name: "Camel Correction Pen", price: 25 },
    { name: "Camel Thick Marker", price: 9 },
    { name: "Faber Castle Marker", price: 18 },
    { name: "Camel White Board Marker", price: 22 },
    { name: "Apasara Pencil Box", price: 50 },
    { name: "Doms Pencil Box", price: 50 },
    { name: "0.5 White Tape", price: 15 },
    { name: "1\" White Tape", price: 25 },
    { name: "2\" White Tape", price: 40 },
    { name: "3\" White Tape", price: 60 },
    { name: "1\" Brown Tape", price: 25 },
    { name: "2\" Brown Tape", price: 40 },
    { name: "3\" Brown Tape", price: 60 },
    { name: "1\" Double Tape(Thin)", price: 20 },
    { name: "2\" Double Tape(Thin)", price: 40 },
    { name: "1\" Foam Double Tape", price: 20 },
    { name: "2\" Foam Double Tape", price: 40 },
    { name: "1\" Color Tape", price: 20 },
    { name: "2\" Color Tape", price: 40 },
    { name: "Invisible Tape & Dispenser", price: 150 },
    { name: "Glue Drop", price: 20 },
    { name: "Blue Tag", price: 150 },
    { name: "Tape Dispenser (Small)", price: 70 },
    { name: "Tape Dispenser (medium)", price: 90 },
    { name: "Tape Dispenser (Big)", price: 120 },
    { name: "Velcro (1 meter)", price: 20 },
    { name: "Correction Tape", price: 60 },
    { name: "Tissue Paper 2 Ply", price: 20 },
    { name: "Tissue Paper 4 Ply", price: 35 },
    { name: "Tissue Paper Box", price: 70 },
    { name: "Tissue Paper Box Maruti", price: 80 },
    { name: "Toilet Tissue Paper (Small)", price: 20 },
    { name: "Toilet Tissue Paper (Big)", price: 40 },
    { name: "Toothpick (Small)", price: 20 },
    { name: "Toothpick (Big)", price: 40 },
    { name: "2x3 ZIP Lock Platic Bags(100 pieces)", price: 30 },
    { name: "2.5x3.5 ZIP Lock Plastic Bags(100 pieces)", price: 35 },
    { name: "3x4 ZIP Lock Plastic Bags(100 pieces)", price: 50 },
    { name: "3x5 ZIP Lock Plastic Bags(100 pieces)", price: 70 },
    { name: "4x6 ZIP Lock Plastic Bags(100 pieces)", price: 100 },
    { name: "5x7 ZIP Lock Plastic Bags(100 pieces)", price: 200 },
    { name: "6x8 ZIP Lock Plastic Bags(100 pieces)", price: 250 },
    { name: "7x10 ZIP Lock Plastic Bags(100 pieces)", price: 300 },
    { name: "9x12 ZIP Lock Plastic Bags(100 pieces)", price: 450 },
    { name: "Blue Bag 27X30 (25 Pieces)", price: 250 },
    { name: "PP Bag Clear (1Kg)", price: 350 }
];
